spring.application.name=ecom

spring.datasource.url=jdbc:postgresql://localhost:5432/ecom_db
spring.datasource.username=hydra_user
spring.datasource.password=odiaca!23
spring.datasource.driver-class-name=org.postgresql.Driver